name: Issue Report
description: Create a new issue with relevant details
title: "Title"
labels: []
assignees: []
projects: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📌 Issue Details
        Please provide a detailed description of the issue, including what needs to be done and how we know it is complete.

  - type: textarea
    id: description
    attributes:
      label: "🔍 Description"
      description: "Provide a clear and concise description of the issue."
      placeholder: "Explain the problem..."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "✅ Acceptance Criteria"
      description: "What must be true for this issue to be considered done?"
    validations:
      required: true


